### ISSUE TITLE
[FIX] 딥러닝 서버 검색 결과에 대해 모호한 속성을 IN 검색 하도록 개선

### ISSUE THREAD

**Issue by YongSiHun** [KNUT-Capstone-Design-team-1/wip-main-server-v2#17]
### 1. 기존 기능 개발 이슈 (개선 하고자 하는 기능에 대한 개발 이슈)
* 없음

### 2. 개요 (한 줄로 간단하게 작성)
* 이미지 검색 시 모호한 속성에 대해 OR 검색을 수행하도록 개선

### 3. AS-IS (현재 상황 / 필요한 이유를 목록으로 작성)
* 알약의 모양 중 '타원형'과 '장방형'의 경우 구분이 어려우며, 제약사마다 기준이 다르다

### 4. TO-BE (목표에 대해 목록으로 작성)
* 모호한 항목에 대해서는 OR로 검색하도록 한다

### 5. 비고 (기타 사항)
*

**Comment by YongSiHun** [comment]
# 작업 계획
- generateQueryFilterForPillSearch() 함수에서 특정 값 (ex '타원형', '장방형')에 대해 IN 쿼리로 변경한다

**Comment by YongSiHun** [comment]
# 작업 결과
- 식별 검색에서 동일한 로직을 사용할 수 있도록 서버에서 아래와 같이 받도록 함
```json
{
    "DRUG_SHAPE": ["장방형", "타원형"]
}
```

# 계획
- DRUG_SHAPE 외 다른 IN 쿼리 항목이 있는지 조사

**Comment by CaffeinCoding** [comment]
DRUG_SHAPE와 같이 IN 쿼리가 필요한 경우
- COLOR_CLASS1
- COLOR_CLASS2

이 2가지 경우가 있을 것 같네요

> 아직 확실하지는 않지만 알약의 문양(CHARTIN)과 글자(PRINT)를 비교할 수 없는 경우가 생길 수 도 있으니 참고 바랍니다
> ex) 'm' 문양과 m 글자일 경우

**Comment by YongSiHun** [comment]
IN 쿼리는 exactly matching이며, AND 검색을 하기 때문에 값을 명확하게 설정해줘야 합니다.
따라서 아래의 케이스를 고려하여 알려주시면 감사드리겠습니다.

- COLOR_CLASS의 경우 '파랑, 투명'과 같이 `투명`이라는 값이 포함된 경우가 있다
  - `{ COLOR_CLASS1: ['파랑', '파랑, 투명'], COLOR_CLASS2: ['파랑', '파랑, 투명'] }`
- COLOR_CLASS1에만 색상 값이 있는 케이스도 많다
  - AND 검색을 할 경우 이러한 케이스 검색을 위해 필터를 잘 만들어야 함
- CHARTIN과 PRINT
  - 구분할 수 없다면 현재와 같이 OR 검색을 수행해야 두 케이스를 조회할 수 있다

**Comment by YongSiHun** [comment]
# 식별 검색 / 이미지 검색 요청 시 데이터 포맷
```ts
export type TPillSearchParam = {
  ITEM_SEQ: string;
  ITEM_NAME: string;
  ENTP_NAME: string;
  COLOR_CLASS1: string;
  COLOR_CLASS2: string;
  PRINT_FRONT: string;
  PRINT_BACK: string;
  LINE_FRONT: string;
  LINE_BACK: string;
  CHARTIN: string;
  DRUG_SHAPE: string[];
};
```

**Comment by YongSiHun** [comment]
# 논의 결과
- 현재 형상대로 진행
